### ISSUE TITLE
Highlighted characters read as separate word

### ISSUE THREAD

**Issue by iowillhoit** [salesforce/design-system-react#449] opened 2016-07-20 13:46 UTC
"Screen reader reads the highlighted characters as a separate word. I don't think we need to do anything right now but it's something to be aware of moving forward. I'll try to do some research and find what the "standard" solution is for highlighted search terms."
--@donnieberg

**Comment by interactivellama** [comment] 2018-04-20 06:53
@arodenbeck Can you look into this? The issue is that if there is a highlight (like in a tree or app launcher), then the screen reader breaks up if there's a span highlighting a partial word.

There may not be an alternative.

**Comment by arodenbeck** [comment] 2018-04-20 14:12
@interactivellama I'll check it out. Some initial thoughts, without having looked at the component yet, certain things will break up a word in this way, so as to indicate there is a difference. Capitalization is something that can cause this. Generally highlighting is not indicated, but there are verbosity settings that will allow the screen reader to announce this.

**Comment by interactivellama** [comment] 2018-05-03 20:53
What is the final verdict on the path forward for this or can I close it?

**Comment by arodenbeck** [comment] 2018-05-08 14:10
@interactivellama I have not gotten very far on this one, so still investigating.

**Comment by arodenbeck** [comment] 2018-05-18 19:45
Screen readers have the option of reading attributes, or not. Typically this feature is disabled for verbosity sake. The fact that letters are broken apart from the rest of a word if only some letters hahve differing attributes is one method for detecting that there is a difference the screen reader user should take note of. They can then explicitly query those letters for attributes, or toggle on the announcement of  all attributes. In my opinion this is expected behavior.

**Closed** 2018-05-18 19:45 UTC
Labels: SLDS-action-needed, accessibility, needs-clarity
