### ISSUE TITLE
Required Input in Error State, error message still there even though field is filled.

### ISSUE THREAD

**Issue by MuizU** [salesforce/design-system-react#1865] opened 2019-03-22 08:59 UTC
The require error message in the Require Input in Error State does not go away once the field is filled. The bug can be observed through the image below.

![DeepinScreenshot_select-area_20190322142711](https://user-images.githubusercontent.com/35157872/54811500-d39fda80-4cae-11e9-88b9-b8ad506d13dd.png)

**Comment by interactivellama** [comment] 2019-03-22 20:42
These are developer examples. Mostly for testing. If you would like to add some state to the parent example component that makes the error away. The project would be open to it. I'm going to close this, since it's not a bug, but feel free to re-open if you want to pull request some additional functionality in the Example code that will end up on the documentation website.

**Closed** 2019-03-22 20:43 UTC
