### ISSUE TITLE
SLDS Icon with dynamic paths cache SVGs

### ISSUE THREAD

**Issue by pianeer** [salesforce/design-system-react#2205] opened 2019-08-01 22:23 UTC
There seems to be an issue with the `SLDSIcon` component when working with the `path` prop. If the `path` value changes dynamically, the SVG seems to be cached for some reason and doesn't update or reflect the new path value. I've run into this issue recently when I had a feature that required moving around table columns that had SVG icons in their headers and for some reason the SVGS would stick to their previous values and not update accordingly.

```
const dynamicVariable = 'dynamic path pointing to a sprite, etc';

return (
<SLDSIcon 
  size="small" 
  className="type-icon"
  path={dynamicVariable}
/>);
```

**Comment by interactivellama** [comment] 2019-08-01 22:45
@kevinparkerson

**Comment by interactivellama** [comment] 2019-08-07 02:58
Do you know if this is a SVG issue related to SVGs being Shadow DOM since SLDS uses `use`?

**Comment by interactivellama** [comment] 2019-08-08 15:18
@pianeer I would recommend re-rendering the whole icon. Maybe some kind of higher order component that has state. In order to change the path inside the SVG shadowDOM, I think you will need to re-mount the icon. 

```
<IconHOC path="" />
  <Icon/>
</IconHOC>
```

**Comment by pianeer** [comment] 2019-08-12 23:14
@interactivellama I could give that a shot but do you suppose there's an easier way out? Just trying to avoid making a one-off fix to get this working on our code-base.

**Comment by interactivellama** [comment] 2019-08-13 04:47
@nik72619c I think a change in key will force a re-render, I think path is the only prop that changes within the SVG shadow DOM. You might try adding a `key` the SVG based on the path, then when the path changes, the key will force a re-mount. It looks like a key has already been implemented, but would only changed you were using SLDS name and category, also. Could that be the issue? Are you all using custom icons, etc?

```
<svg key={`${name}_${category}`} {...rest}>
    <use xlinkHref={modifiedPath} />
</svg>
```
Look at https://github.com/salesforce/design-system-react/blob/master/components/utilities/utility-icon/index.jsx#L79 and see if that could be the issue. What's the name and category being used and is it being updated when the path changes?

This makes me wonder if the path should be a part of that `key` also.

**Comment by interactivellama** [comment] 2019-08-13 04:48
@pianeer  I think a change in key will force a re-render, I think path is the only prop that changes within the SVG shadow DOM. You might try adding a `key` the SVG based on the path, then when the path changes, the key will force a re-mount. It looks like a key has already been implemented, but would only changed you were using SLDS name and category, also. Could that be the issue? Are you all using custom icons, etc?

```
<svg key={`${name}_${category}`} {...rest}>
    <use xlinkHref={modifiedPath} />
</svg>
```
Look at https://github.com/salesforce/design-system-react/blob/master/components/utilities/utility-icon/index.jsx#L79 and see if that could be the issue. What's the name and category being used and is it being updated when the path changes?

This makes me wonder if the path should be a part of that `key` also.

**Comment by pianeer** [comment] 2019-08-13 05:14
@interactivellama We need to leverage the `path` prop in this case because there isn't a name and category. It's a custom SVG icon(not defined in SLDS) specific to Analytics.

**Comment by interactivellama** [comment] 2019-08-15 23:00
@pianeer Looking at @kevinparkerson  and my release plans. I can add the `icon` key update to our backlog in early September if you'd like. If you want something before then, please submit a pull request and I can review it next week.

**Comment by pianeer** [comment] 2019-08-16 16:38
Thanks for the update @interactivellama. We have a workaround by using our legacy SVG icon component for now. So I can wait until next month. If I can however get some free time, I maybe able to submit a PR too.

**Comment by interactivellama** [comment] 2019-08-16 16:41
Sounds good.

**Comment by interactivellama** [comment] 2019-08-16 18:52
FYI: @garygong @Prophetess

**Comment by garygong** [comment] 2020-04-04 04:37
@interactivellama When I tried reproducing this problem, I don't see this problem happening.  We can add `path` to the `<svg>` key anyway though.  What do you think?

**Comment by garygong** [comment] 2020-04-08 21:24
Closing this issue because I can't reproduce it.  If you see this problem happening again, please reopen.  Thanks!

**Closed by garygong** 2020-04-08 21:24 UTC
Labels: icon

**Comment by nangnh** [comment] 2023-03-07 16:13
My response to your problem is this. My Vuejs project is working well.
`<svg class="slds-button__icon slds-button__icon_left" aria-hidden="true">
        <use
          :xlink:href="require('@/assets/vendor/slds/assets/icons/utility-sprite/svg/symbols.svg') + `#${iconName}`"
        ></use>
      </svg>`
